version: "3.8"

services:
  web:
    image: nginx:latest
    container_name: web
    ports:
      - "8080:80" # Expose port 8080 on the host, mapping to port 80 inside the container
    networks:
      - my-network

  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432" # Expose port 5432 on the host for PostgreSQL
    networks:
      - my-network
    volumes:
      - db-data:/var/lib/postgresql/data # Persist database data

networks:
  my-network:
    driver: bridge

volumes:
  db-data:
